### ISSUE TITLE
please update f-driod version

### ISSUE THREAD

**Issue by leela52452** [enricocid/Storage-USB#2]
@enricocid [README](https://github.com/enricocid/Storage-USB/blob/master/README.md) states that version 2.0.3 is available.

can you please update app on f-droid or create tag or something like that.

**Comment by enricocid** [comment]
2.0.3 was added (and 2.0.2 tag removed) for the Google Play Store as in 2.0.2 I forgot to bump version code and was unable to upload it on gplay. So I was forced to bump version.
Anyway, tag 2.0.2 was uploaded on F-Droid and 2.0.3 (which is already present) not because it doesn't contain code changes. 

So You can consider 2.0.2 as the last version.

**Comment by leela52452** [comment]
thank you
